Move tests to the flake
nickel-lang/nickel-nix pull request #74
Opened 2023-06-02 15:39 UTC by YorikSar

Create "devshell" for each test that can be executed with `nix develop` and call it from GitHub workflows.
This allows to run tests locally with high confidence that they will pass on CI.

Depends on #73

2023-06-14 20:12 UTC, YorikSar commented
@yannham @thufschmitt I'd appreciate a review on this one as well.

2023-06-15 04:48 UTC, thufschmitt requested changes
I like the idea of moving that out of the workflows file, but making these tests devshells feels a bit weird. We don't care about the shell part at all, all we care about is running the test script. Could we instead export these scripts as `packages` so that we can do `nix run .#tests.templates.c` or something like that?

Also, we could have only one script that takes the template name as argument and run it through `nix run .#test.templates c` (though I don't have a strong opinion here)

2023-06-15 05:04 UTC, YorikSar commented
I got three idea of using devshells for this from home-manager: https://github.com/nix-community/home-manager/blob/master/flake.nix#L90 - for some reason they didn't do them as packages or apps. I see how strange this decision looks without context now.
I'll move them to packages (or apps? nobody  would use them as packages, right?).

I like having this enumeration of tests in Nix, it leaves less logic to differ between CI and dev environment. But we could have both approaches: attributes for CI and argument in case it's more comfortable for dev.

2023-06-15 05:14 UTC, YorikSar commented
Oh, right. Having them as shells allows to easily run them without `nix run` command using `nix-shell`. That's why they went this way most likely. It doesn't apply to us at all.

2023-06-15 11:05 UTC, YorikSar commented
@thufschmitt I've moved tests to apps, now it's clear that you can only run them, but not build them.

2023-06-15 14:41 UTC, thufschmitt approved these changes
Thanks!

2023-06-15 14:41 UTC, merged